import propTypes from 'prop-types'
import './globals.css'

export const metadata = {
  title: 'SALUS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}

RootLayout.propTypes = {
  children: propTypes.node,
}
